# Site settings
title: John Hughes
description: Web development and other interesting things
url: http://johnhughesweb.co.uk
email: hello@johnhughesweb.co.uk
twitter: johnkhughes
github: johnkhughes

# Build settings
permalink: /:year/:month/:title/

exclude:
  - LICENSE
  - README.md

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

markdown: kramdown

kramdown:
  auto_ids: false
  entity_output: as_char
  smart_quotes: lsquo,rsquo,ldquo,rdquo

# Archive settings
gems:
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
    - tags
    - year
    - month
  layouts:
    category: category
    tag: tag
    year: year
    month: month
