title: John Hughes
description: Web development and other interesting things
url: https://www.johnhughesweb.co.uk
author: John Hughes
email: hello@johnhughesweb.co.uk

github: johnkhughes
gitlab: jkhughes
twitter: johnkhughes

date_format: "%e %B %Y"
permalink: /:year/:month/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
